name: newspaper_scraper
on: workflow_dispatch

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Installed package list
        run: apt list --installed
      - name: Install necessary packages
        run: sudo apt install git libxml2-dev libxslt-dev python3-dev python3-lxml
      - name: Install all necessary python modules
        run: pip install -r requirements.txt
      - name: Expose GitHub secrets as individual environment variables
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          secrets=$(echo "$SECRETS_CONTEXT" | jq -r 'to_entries[] | select(.key != "WG_CONFIG_FILE") | .key + "=" + .value')
          echo "$secrets" >> $GITHUB_ENV
      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
        # Send connection info to Telegram (optional)
        # You can find related documents here: https://core.telegram.org/bots
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.ERROR_MESSAGE_CHAT_ID }}
      - name: Set up WireGuard Connection
        uses: niklaskeerl/easy-wireguard-action@v2
        with:
          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}
      - name: Run the script
        run: python main.py
        working-directory: .
