name: newspaper_scraper
on: 
  workflow_dispatch:
    inputs:
      triggered_by:
        description: 'Who triggered this workflow'
        required: false
        default: 'manual'
        type: string
      timestamp:
        description: 'When this workflow was triggered'
        required: false
        type: string
# on:
#   schedule:
#     - cron: "*/30 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Check out this repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
        id: setup-python

      - name: Cache Pip packages
        id: cache-pip
        uses: actions/cache@v4
        with:
          # Pip's cache directory
          path: ~/.cache/pip
          # A key that includes the OS, Python version, and a hash of the requirements file.
          # The cache is invalidated only when the requirements file changes.
          key: ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/requirements.txt') }}
          # A fallback key to use the most recent cache if the exact key isn't found
          restore-keys: |
            ${{ runner.os }}-pip-${{ steps.setup-python.outputs.python-version }}-
            ${{ runner.os }}-pip-

      - name: Cache Apt packages
        id: cache-apt
        uses: actions/cache@v4
        with:
          # Apt's package archive directory
          path: /var/cache/apt/archives
          # A key that includes the OS and a hash of this workflow file.
          # The cache is invalidated only when you change the list of apt packages in this file.
          key: ${{ runner.os }}-apt-cache-${{ hashFiles('.github/workflows/newspaper_scraper.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-cache-

      - name: Installed package list
        run: apt list --installed
      - name: Update repo
        run: sudo apt-get update
      - name: Install necessary packages
        run: sudo apt-get install -y --no-install-recommends git libxml2-dev libxslt-dev python3-dev python3-lxml
      - name: Install all necessary python modules
        # Only run this step if the pip cache was not restored from an exact key match
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: pip install -r requirements.txt
      - name: Expose GitHub secrets as individual environment variables
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: |
          secrets=$(echo "$SECRETS_CONTEXT" | jq -r 'to_entries[] | select(.key != "WG_CONFIG_FILE") | .key + "=" + .value')
          echo "$secrets" >> $GITHUB_ENV
      # - name: Start SSH via tmate
      #   uses: P3TERX/ssh2actions@main
      #   # Send connection info to Telegram (optional)
      #   # You can find related documents here: https://core.telegram.org/bots
      #   env:
      #     TELEGRAM_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      #     TELEGRAM_CHAT_ID: ${{ secrets.ERROR_MESSAGE_CHAT_ID }}
      # - name: Set up WireGuard Connection
      #   uses: niklaskeerl/easy-wireguard-action@v2
      #   with:
      #     WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}
      - name: Run the script
        run: python main.py
        working-directory: .
